mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

""" Django starts at the first regular expression and makes
its way down the list, comparing the requested URL against
each regular expression until it finds one that matches. """

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.conf.urls import url

from . import views

""" Django starts at the first regular expression and makes
its way down the list, comparing the requested URL against
each regular expression until it finds one that matches. """

app_name = 'polls'
urlpatterns = [
    # index
    url(r'^index/$', views.index, name='index'),

    # logout
    url(r'^odjava/$', views.logout_user, name='logout_user'),

    # login
    url(r'^prijava/$', views.login_user, name='login_user'),

    # about us
    url(r'^o_nas/$', views.about, name='about'),

    # fuel station detail
    url(r'^crpalka/(?P<fuel_station_id>[0-9]+)/$', views.detail, name='detail'),

    # advanced search
    url(r'^napredno_iskanje/(?P<location>[a-zA-ZžŽčČšŠ]+( [a-zA-ZžŽčČšŠ]+)*)/(?P<fuel_type>[0-9a-zA-Z]+)/$',
        views.advanced_search, name='advanced_search'),
    url(r'^napredno_iskanje/$', views.advanced_search, name='advanced_search'),

    # trip planner
    url(r'^nacrtovalec_poti/$', views.route_planner, name='route_planner'),

    # search location
    url(r'^search_location/$', views.search_location, name='search_location'),
]

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _

WEEKDAYS = [
  (1, _("Monday")),
  (2, _("Tuesday")),
  (3, _("Wednesday")),
  (4, _("Thursday")),
  (5, _("Friday")),
  (6, _("Saturday")),
  (7, _("Sunday")),
]


class FuelStation(models.Model):
    """ A model which defines a single fuel station. """
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=200)
    location = models.CharField(max_length=200)
    region = models.CharField(max_length=200)
    long = models.DecimalField(max_digits=9, decimal_places=6, default='0.0')
    lang = models.DecimalField(max_digits=9, decimal_places=6, default='0.0')
    rating = models.FloatField('avg. rating', default=-1.0)

    price_95 = models.FloatField('95 octane fuel price', default=-1.0)
    price_98 = models.FloatField('98 octane fuel price', default=-1.0)
    price_100 = models.FloatField('100 octane fuel price', default=-1.0)
    price_diesel = models.FloatField('diesel fuel price', default=-1.0)

    def get_fuel_price(self, fuel_type='95'):
        if fuel_type == '95':
            return self.price_95
        if fuel_type == '100':
            return self.price_100
        if fuel_type == '98':
            return self.price_98
        return self.price_diesel

    def __str__(self):
        return self.name + ", " + self.address


class OpeningHours(models.Model):
    fuel_station_id = models.ForeignKey(FuelStation)
    weekday_from = models.IntegerField(choices=WEEKDAYS, unique=True)
    weekday_to = models.IntegerField(choices=WEEKDAYS)
    from_hour = models.TimeField()
    to_hour = models.TimeField()

    def get_weekday_from_display(self):
        return WEEKDAYS[self.weekday_from]

    def get_weekday_to_display(self):
        return WEEKDAYS[self.weekday_to]


class Evaluation(models.Model):
    comment = models.TextField()
    rating = models.IntegerField()
    pub_date = models.DateTimeField('date published')
    fuel_station_id = models.ForeignKey(FuelStation)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    # When the referenced object is deleted, also delete the objects
    # that have references to it

    class Meta:
        permissions = (
            ('edit_evaluation', 'Can remove evaluation/comment.'),
        )

    def __str__(self):
        return '{} {} {}'.format(self.rating, self.user_id,
                                 self.fuel_station_id)


@receiver(post_delete)
def update_rating(sender, instance=None, created=False, **kwargs):
    """ Listen & Trigger upon a rating change (deletion, insertion). """
    if sender.__name__ in ('Evaluation', ) and instance is not None:
        fuel_station = instance.fuel_station_id

        evaluations = Evaluation.objects.filter(
            fuel_station_id=fuel_station.id)

        fuel_station.rating = (sum([smh.rating for smh in evaluations])
                               * 1.0 / len(evaluations))

        fuel_station.save()


@receiver(post_save)
def another_update_rating(sender, instance=None, created=False, **kwargs):
    """ Listen & Trigger upon a rating change (deletion, insertion). """
    if sender.__name__ in ('Evaluation', ) and instance is not None:
        fuel_station = instance.fuel_station_id

        evaluations = Evaluation.objects.filter(
            fuel_station_id=fuel_station.id)

        fuel_station.rating = (sum([smh.rating for smh in evaluations])
                               * 1.0 / len(evaluations))

        fuel_station.save()

mysite/polls/forms.py
from django import forms


class LoginForm(forms.Form):
    """ Validate login form. """
    username = forms.CharField(label='username', max_length=50)
    password = forms.CharField(max_length=50, widget=forms.PasswordInput)


class RegistrationForm(forms.Form):
    """ Validate registration form. """
    new_username = forms.CharField(label='username', max_length=50)
    password = forms.CharField(max_length=50, widget=forms.PasswordInput)
    password_again = forms.CharField(max_length=50, widget=forms.PasswordInput)

mysite/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

from .models import FuelStation, Evaluation, OpeningHours
from .forms import LoginForm, RegistrationForm


SKLANJANJE = {
    'Ljubljana': 'Ljubljani',
    'Maribor': 'Mariboru',
    'Novo mesto': 'Novem mestu',
}


def index(request):
    # latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', {})


def about(request):
    return render(request, 'polls/about.html', {})


def detail(request, fuel_station_id):
    fuel_station = get_object_or_404(FuelStation, pk=fuel_station_id)
    prices = [(smh + '-oktanski' if smh != 'diesel' else 'Dizel',
               "%.3f" % fuel_station.get_fuel_price(smh))
              for smh in ('95', '98', '100', 'diesel')
              if fuel_station.get_fuel_price(smh) > 0]

    return render(request,
                  'polls/detail.html',
                  {'fuel_station': fuel_station,
                   'prices': prices})


def advanced_search(request, location='Ljubljana', fuel_type='95'):
    fuel_stations_list = FuelStation.objects.filter(location=location)

    fuel_stations_list = sorted([smh for smh in fuel_stations_list
                                 if smh.get_fuel_price(fuel_type) > 0],
                                key=lambda x: x.get_fuel_price(fuel_type),
                                reverse=False)

    avg_price = (sum([smh.get_fuel_price(fuel_type) for smh in
                      fuel_stations_list]) * 1.0 / len(fuel_stations_list)
                 if fuel_stations_list else '-')

    lowest_price = (min(smh.get_fuel_price(fuel_type)
                        for smh in fuel_stations_list)
                    if fuel_stations_list else '-')

    context = {'fuel_stations_list': fuel_stations_list,
               'location': SKLANJANJE.get(location, 'Ljubljani'),
               'fuel_type': fuel_type,
               'avg_price': "%.3f" % avg_price if
               type(avg_price) == float else avg_price,
               'lowest_price': "%.3f" % lowest_price if
               type(lowest_price) == float else lowest_price}

    return render(request, 'polls/advanced_search.html', context)


def search_location(request):
    args = ()
    if request.method == "POST":
        location = request.POST['t_location'] or 'Ljubljana'
        fuel_type = request.POST['t_fuel_type'].split('-')[0] or '95'
        args = (location, fuel_type)
    return HttpResponseRedirect(reverse('polls:advanced_search',
                                        args=args))


def route_planner(request):
    return render(request, 'polls/route_planner.html', {})


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('polls:index', args=()))


def login_user(request):
    if request.method == "POST":
        if 'new_username' in request.POST:
            # registration
            form = RegistrationForm(request.POST)
            if form.is_valid():
                user = User.objects.create_user(
                    username=form.cleaned_data['new_username'],
                    password=form.cleaned_data['password'])
            else:
                return render(request, 'polls/login_user.html',
                              {'error_msg': 'Registration failed. Try again!'})

        else:
            # existing user login
            form = LoginForm(request.POST)
            if form.is_valid():
                user = authenticate(username=form.cleaned_data['username'],
                                    password=form.cleaned_data['password'])
            else:
                return render(request, 'polls/login_user.html',
                              {'error_msg': 'Login failed. Try again!'})

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('polls:index', args=()))
        else:
            return render(request, 'polls/login_user.html',
                          {'error_msg': 'Wrong credentials. Try again!'})

    return render(request, 'polls/login_user.html', {})

mysite/polls/templates/polls/about.html
{% extends "polls/base.html" %}

{% block title %} O nas {% endblock %}

{% block content %}
    <div>
        <p>
            Janez Novak <br/>
            Večna pot 113 <br/>
            041 444 666
        </p>
    </div>
{% endblock %}

mysite/polls/templates/polls/advanced_search.html
{% extends "polls/base.html" %}
{% load static %}

{% block title %} Napredno iskanje {% endblock %}

{% block content %}

    <form action="{% url 'polls:search_location' %}" method="post" id="get_options_01">
    {% csrf_token %}
    <div class="search-filters">
        <span><input name="t_location" class="loc-search-box" type="text" placeholder="Poišči cene glede na lokacijo .. "/><button class="search-button"><img src="{% static 'polls/images/searchicon.png' %}" alt="ni slike"/></button></span>
        <span><select name="t_fuel_type" form="get_options_01">
            <option>95-oktanski</option>
            <option>98-oktanski</option>
            <option>100-oktanski</option>
            <option>Dizel</option>
        </select><img src="{% static 'polls/images/gaspumpicon.png' %}" alt="ni slike" class="crpalka"/><button class="gpsbutton"><img src="{% static 'polls/images/gps.png' %}" alt="ni slike"/></button></span>
    </div>
    </form>

    <div class="title-row">Najnižje cene v {{ location }}</div>
    <div>
        <table id="tabelca" class="seznam-crpalk">
        {% for fuel_station in fuel_stations_list %}
            <tr><td>{% if fuel_type == '95' %} {{ fuel_station.price_95 }} {% elif fuel_type == '98' %} {{ fuel_station.price_98 }} {% elif fuel_type == '100' %} {{ fuel_station.price_100 }} {% else %} {{ fuel_station.price_diesel }} {% endif %}</td>
                <td><span><a href="{% url 'polls:detail' fuel_station.id %}">{{ fuel_station.name }}</a></span><br/>{{ fuel_station.address }}</td>
                <td>{{ fuel_station.region }} regija</td>
                <td>3m nazaj</td>
            </tr>
        {% endfor %}
        <td onclick="vstavi()" colspan="4">Oglejte si več cen</td></tr>
        </table>
    </div>

{% endblock %}

<hr />

{% block subcontent %}

<section>
    <table>
        <tr>
            <td colspan="3">Analiza prikazanih <hr /></td>
        </tr>
        <tr>
            <td>Povprečna cena <br> <span>{{ avg_price }}</span></td>
            <td>Najnižja cena <br> <span>{{ lowest_price }}</span></td>
            <td>Trend spreminjanja<br> <span><img src="{% static 'polls/images/gor.png' %}" alt="ni slike"></span></td>
        </tr>
    </table>
</section>

{% endblock %}

mysite/polls/templates/polls/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Pumpa.si {% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/layout.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/media.css' %}">
    <script src="{% static 'polls/page.js' %}"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
</head>
<body>

<header>
    <nav>
        <div>
            <a href="{% url 'polls:index' %}"><img class="logo" src="{% static 'polls/images/logo.png' %}" alt="ni slike"/></a>
        </div>
        <div>
            <a href="{% url 'polls:advanced_search' %}">Napredno iskanje</a>
        </div>
        <div>
            <a href="{% url 'polls:route_planner' %}">Načrtovalec poti</a>
        </div>
        <div>
            <a href="{% url 'polls:about' %}">O nas</a>
        </div>
        <div>
            {% if user.is_authenticated %}
            &nbsp &nbsp &nbsp{{user.username}}:<a href="{% url 'polls:logout_user' %}">Odjavi</a>
            {% else %}
            <a href="{% url 'polls:login_user' %}">Prijava</a>
            {% endif %}
        </div>
    </nav>

    <hr />

</header>

<main>
    {% block content %} {% endblock %}
</main>

{% block subcontent %} {% endblock %}

</body>
</html>

mysite/polls/templates/polls/detail.html
{% extends "polls/base.html" %}
{% load static %}

{% block title %} Podatki o črpalki {% endblock %}

{% block content %}

<div>
    <table class="ena-crpalka">
        <tr>
            <td>{{ fuel_station.name }}</td>
            <td>{{ fuel_station.address }}</td>
            <td>ODPRTO</td>
            <td>3m nazaj</td>
        </tr>
    </table>

</div>

    <div class="cene-goriv">
        {% for price in prices %}
        <div>{{ price.0 }} <hr /><span> {{ price.1 }}</span></div>
        {% endfor %}
    </div>

    <div class="odpiralni_cas">
        <div>Odpiralni čas <hr />
        <table class="urnik">
            <tr><td>PONEDELJEK</td> <td>06:00 - 22:00</td></tr>
            <tr><td>TOREK</td> <td>06:00 - 22:00</td></tr>
            <tr><td>SREDA</td> <td>06:00 - 22:00</td></tr>
            <tr><td>ČETRTEK</td> <td>06:00 - 22:00</td></tr>
            <tr><td>PETEK</td> <td>06:00 - 22:00</td></tr>
            <tr><td>SOBOTA</td> <td>06:00 - 22:00</td></tr>
            <tr><td>NEDELJA</td> <td>06:00 - 22:00</td></tr>
        </table>
        </div>
    </div>

{% endblock %}

mysite/polls/templates/polls/index.html
{% load static %}

{#<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />#}
{##}
{#{% if latest_question_list %}#}
{#    <ul>#}
{#    {% for question in latest_question_list %}#}
{#        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>#}
{#    {% endfor %}#}
{#    </ul>#}
{#{% else %}#}
{#    <p>No polls are available.</p>#}
{#{% endif %}#}


<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Google Maps with data input table</title>
    <script src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <style>
        a#msg {
            font-size: 11px;
            font-family: arial;
            text-decoration: none;
            color: black;
            display:inline-block;
            padding: 5px 0;
            border-bottom: 2px dotted lightgrey;
        }
        #map {
            height: 100%;
            width: 100%;
            position:absolute;
            top: 0;
            left: 0;
            z-index: 0;
            opacity: .75;
        }
        .gmnoprint:not(.gm-bundled-control) {
            display: none;
        }

        .gm-bundled-control .gmnoprint {
            display: block;
        }
        a[href^="http://maps.google.com/maps"]{display:none !important}
        a[href^="https://maps.google.com/maps"]{display:none !important}
        a[href^="https://www.google.com/maps"]{display:none !important}
        #info {
            position: absolute;
            z-index: 1;
            width: 300px;
            margin: 50px auto 0;
        }
        input, textarea {
            border: none;
            outline: none;
            resize: none;
            width: 100%;
            -moz-appearance: none;
            -webkit-appearance: none;
            font-size: 13px;
            margin: 0;
            padding: 0;
        }
        .contact-form {
            background: white;
            height: auto;
            max-width: 350px;
            overflow: hidden;
            width: 250px;
            -moz-border-radius: 5px;
            -webkit-border-radius: 5px;
            border-radius: 5px;
            -moz-box-shadow: rgba(26, 26, 26, 0.1) 0 1px 3px 0;
            -webkit-box-shadow: rgba(26, 26, 26, 0.1) 0 1px 3px 0;
            box-shadow: rgba(26, 26, 26, 0.1) 0 1px 3px 0;
        }
        @media (max-width: 500px) {
            .contact-form {
                margin: 0 0 100px;
                width: 100%;
            }
        }
        .contact-form .email, .contact-form .message, .contact-form .name {
            position: relative;
        }
        .contact-form .email input:focus, .contact-form .email textarea:focus, .contact-form .message input:focus, .contact-form .message textarea:focus, .contact-form .name input:focus, .contact-form .name textarea:focus {
            background: #f4f5f6;
        }
        @media (max-width: 500px) {
            .contact-form .email, .contact-form .name {
                width: 100%;
            }
        }
        .contact-form .email input, .contact-form .name input {
            padding: 23px 0 8px 23px;
        }
        .contact-form .email {
            border-left: 1px #e6e6e6 solid;
            float: right;
        }
        @media (max-width: 500px) {
            .contact-form .email {
                border-left: none;
                border-top: 1px #e6e6e6 solid;
            }
        }
        .contact-form .message {
            border-bottom: 1px #e6e6e6 solid;
            border-top: 1px #e6e6e6 solid;
            clear: both;
        }
        .contact-form .message textarea {
            height: 100px;
            padding: 20px;
        }
        .contact-form .name {
            float: left;
        }
        .contact-form .submit {
            background: #f4f5f6;
            display: block;
            overflow: hidden;
            padding: 10px;
        }
        .contact-form .submit .button {
            background: #3498db;
            border: 1px #3498db solid;
            color: white;
            float: right;
            padding: 9px 0;
            width: 100px;
            -moz-border-radius: 5px;
            -webkit-border-radius: 5px;
            border-radius: 5px;
        }
        @media (max-width: 500px) {
            .contact-form .submit .button {
                float: none;
            }
        }
        .contact-form .submit .button:hover {
            background: #4aa3df;
        }
        .contact-form .submit .button:active {
            background: #258cd1;
        }
        .contact-form .submit .button:focus {
            border-color: #b6daf2;
            -moz-box-shadow: #75b9e7 0 0 4px 1px, #75b9e7 0 0 4px 1px inset;
            -webkit-box-shadow: #75b9e7 0 0 4px 1px, #75b9e7 0 0 4px 1px inset;
            box-shadow: #75b9e7 0 0 4px 1px, #75b9e7 0 0 4px 1px inset;
        }
        .contact-form .submit .user-message {
            float: left;
            padding-top: 22px;
        }
        @media (max-width: 500px) {
            .contact-form .submit .user-message {
                float: none;
                padding: 0 0 10px;
            }
        }
    </style>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/first_page.css' %}">
</head>

<body>

<div id="map"></div>

<div id="info">

    <form class="contact-form">
        <div>
            <img class="logo" src="{% static 'polls/images/logo.png' %}"/>
        </div>
        <select>
            <option>95-oktanski</option>
            <option>98-oktanski</option>
            <option>100-oktanski</option>
            <option>Dizel</option>
        </select><img height="32" src="{% static 'polls/images/gaspumpicon.png' %}" class="crpalka"/>
        <button class="gpsbutton"><img src="{% static 'polls/images/gps.png' %}"/></button>
    </form>
</div>

<div id="navbar">
    <nav>
        <a href="{% url 'polls:advanced_search' %}">Napredno iskanje</a>
        <a href="{% url 'polls:route_planner' %}">Načrtovalec poti</a>
        <a href="{% url 'polls:about' %}">O nas</a>
    </nav>
</div>

<script>
    var position = [46.056946, 14.505751];

    function initialize() {

        var myOptions = {
            zoom: 6,
            streetViewControl: false,
            scaleControl: true,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };

        map = new google.maps.Map(document.getElementById('map'),
                myOptions);


        latLng = new google.maps.LatLng(position[0], position[1]);

        map.setCenter(latLng);

        marker = new google.maps.Marker({
            position: latLng,
            map: map,
            draggable: false,
            animation: google.maps.Animation.DROP
        });

    }

    google.maps.event.addDomListener(window, 'load', initialize);
</script>
</body>

</html>

mysite/polls/templates/polls/login_user.html
{% extends "polls/base.html" %}
{% load static %}

{% block title %} Prijava/registracija uporabnika{% endblock %}

{% block content %}

<h1>{{ error_msg }}</h1>

<form name="login_user" method="post" action="{% url 'polls:login_user' %}">
    <p>Existing user login:</p>
    {% csrf_token %}
    <input type="text" name="username" placeholder="Username"> <br />
    <input type="text" name="password" placeholder="Password"> <br />
    <input type="submit" value="Login"/>
</form>

<br />
<br/>

<form name="register_user" method="post" action="{% url 'polls:login_user' %}">
    <p>New user registration:</p>
    {% csrf_token %}
    <input type="text" name="new_username" placeholder="Pick a username"> <br />
    <input type="text" name="password" placeholder="Password"> <br />
    <input type="text" name="password_again" placeholder="Password again"> <br />
    <input type="submit" value="Register"/>
</form>

{% endblock %}

mysite/polls/templates/polls/route_planner.html
{% extends "polls/base.html" %}
{% load static %}

{% block title %} Načrtovalec poti {% endblock %}

{% block content %}

    <form name="vnos-nacrtuj" class="nacrtovalec" onsubmit="return validate_poraba()" method="post">
        <div class="vnos">
            <p>Vnesite začetno in ciljno lokacijo<br></p>
            <input type="text" name="zacetek" placeholder="Začetek">
            <input type="text" name="konec" placeholder="Cilj">
            <input type="text" name="povprecna-poraba" placeholder="Povprečna poraba 7,5 L/100km">
        </div>
        <br />
        <div class="pojdi">
        <input type="submit" name="go" value="Pojdi">
        </div>
    </form>

{% endblock %}